export const countryData = [
    {
        "name": "Saudi Arabia",
        "officialName": "Kingdom of Saudi Arabia",
        "subregion": "Western Asia",
        "population": 34813867,
        "flag": "https://flagcdn.com/w320/sa.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 3
    },
    {
        "name": "Cameroon",
        "officialName": "Republic of Cameroon",
        "subregion": "Middle Africa",
        "population": 26545864,
        "flag": "https://flagcdn.com/w320/cm.png",
        "yellowFever": true,
        "typhoid": true,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 2
    },
    {
        "name": "Iran",
        "officialName": "Islamic Republic of Iran",
        "subregion": "Southern Asia",
        "population": 83992953,
        "flag": "https://flagcdn.com/w320/ir.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 4
    },
    {
        "name": "United Arab Emirates",
        "officialName": "United Arab Emirates",
        "subregion": "Western Asia",
        "population": 9890400,
        "flag": "https://flagcdn.com/w320/ae.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 2
    },
    {
        "name": "Ukraine",
        "officialName": "Ukraine",
        "subregion": "Eastern Europe",
        "population": 44134693,
        "flag": "https://flagcdn.com/w320/ua.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 4
    },
    {
        "name": "Benin",
        "officialName": "Republic of Benin",
        "subregion": "Western Africa",
        "population": 12123198,
        "flag": "https://flagcdn.com/w320/bj.png",
        "yellowFever": true,
        "typhoid": true,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 2
    },
    {
        "name": "Saint Kitts and Nevis",
        "officialName": "Federation of Saint Christopher and Nevis",
        "subregion": "Caribbean",
        "population": 53192,
        "flag": "https://flagcdn.com/w320/kn.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 0
    },
    {
        "name": "British Indian Ocean Territory",
        "officialName": "British Indian Ocean Territory",
        "subregion": "Eastern Africa",
        "population": 3000,
        "flag": "https://flagcdn.com/w320/io.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 0
    },
    {
        "name": "Indonesia",
        "officialName": "Republic of Indonesia",
        "subregion": "South-Eastern Asia",
        "population": 273523621,
        "flag": "https://flagcdn.com/w320/id.png",
        "yellowFever": false,
        "typhoid": true,
        "malaria": true,
        "jEncephalitis": true,
        "visaRequired": true,
        "travelAdvisory": 2
    },
    {
        "name": "Togo",
        "officialName": "Togolese Republic",
        "subregion": "Western Africa",
        "population": 8278737,
        "flag": "https://flagcdn.com/w320/tg.png",
        "yellowFever": true,
        "typhoid": true,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 1
    },
    {
        "name": "Brunei",
        "officialName": "Nation of Brunei, Abode of Peace",
        "subregion": "South-Eastern Asia",
        "population": 437483,
        "flag": "https://flagcdn.com/w320/bn.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": true,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Czech Republic",
        "officialName": "Czechia",
        "subregion": "Central Europe",
        "population": 10698896,
        "flag": "https://flagcdn.com/w320/cz.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Serbia",
        "officialName": "Republic of Serbia",
        "subregion": "Southeast Europe",
        "population": 6908224,
        "flag": "https://flagcdn.com/w320/rs.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 2
    },
    {
        "name": "Papua New Guinea",
        "officialName": "Independent State of Papua New Guinea",
        "subregion": "Melanesia",
        "population": 8947027,
        "flag": "https://flagcdn.com/w320/pg.png",
        "yellowFever": false,
        "typhoid": true,
        "malaria": true,
        "jEncephalitis": true,
        "visaRequired": true,
        "travelAdvisory": 3
    },
    {
        "name": "Nauru",
        "officialName": "Republic of Nauru",
        "subregion": "Micronesia",
        "population": 10834,
        "flag": "https://flagcdn.com/w320/nr.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 1
    },
    {
        "name": "Bermuda",
        "officialName": "Bermuda",
        "subregion": "North America",
        "population": 63903,
        "flag": "https://flagcdn.com/w320/bm.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Venezuela",
        "officialName": "Bolivarian Republic of Venezuela",
        "subregion": "South America",
        "population": 28435943,
        "flag": "https://flagcdn.com/w320/ve.png",
        "yellowFever": true,
        "typhoid": false,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 4
    },
    {
        "name": "Mayotte",
        "officialName": "Department of Mayotte",
        "subregion": "Eastern Africa",
        "population": 226915,
        "flag": "https://flagcdn.com/w320/yt.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 0
    },
    {
        "name": "Romania",
        "officialName": "Romania",
        "subregion": "Southeast Europe",
        "population": 19286123,
        "flag": "https://flagcdn.com/w320/ro.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Tuvalu",
        "officialName": "Tuvalu",
        "subregion": "Polynesia",
        "population": 11792,
        "flag": "https://flagcdn.com/w320/tv.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 1
    },
    {
        "name": "Palestine",
        "officialName": "State of Palestine",
        "subregion": "Western Asia",
        "population": 4803269,
        "flag": "https://flagcdn.com/w320/ps.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 4
    },
    {
        "name": "China",
        "officialName": "People's Republic of China",
        "subregion": "Eastern Asia",
        "population": 1402112000,
        "flag": "https://flagcdn.com/w320/cn.png",
        "yellowFever": false,
        "typhoid": true,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 3
    },
    {
        "name": "Sri Lanka",
        "officialName": "Democratic Socialist Republic of Sri Lanka",
        "subregion": "Southern Asia",
        "population": 21919000,
        "flag": "https://flagcdn.com/w320/lk.png",
        "yellowFever": false,
        "typhoid": true,
        "malaria": false,
        "jEncephalitis": true,
        "visaRequired": true,
        "travelAdvisory": 2
    },
    {
        "name": "South Africa",
        "officialName": "Republic of South Africa",
        "subregion": "Southern Africa",
        "population": 59308690,
        "flag": "https://flagcdn.com/w320/za.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 2
    },
    {
        "name": "Guernsey",
        "officialName": "Bailiwick of Guernsey",
        "subregion": "Northern Europe",
        "population": 62999,
        "flag": "https://flagcdn.com/w320/gg.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 0
    },
    {
        "name": "Tanzania",
        "officialName": "United Republic of Tanzania",
        "subregion": "Eastern Africa",
        "population": 59734213,
        "flag": "https://flagcdn.com/w320/tz.png",
        "yellowFever": false,
        "typhoid": true,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 2
    },
    {
        "name": "Guadeloupe",
        "officialName": "Guadeloupe",
        "subregion": "Caribbean",
        "population": 400132,
        "flag": "https://flagcdn.com/w320/gp.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 0
    },
    {
        "name": "Faroe Islands",
        "officialName": "Faroe Islands",
        "subregion": "Northern Europe",
        "population": 48865,
        "flag": "https://flagcdn.com/w320/fo.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 0
    },
    {
        "name": "Tokelau",
        "officialName": "Tokelau",
        "subregion": "Polynesia",
        "population": 1411,
        "flag": "https://flagcdn.com/w320/tk.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 0
    },
    {
        "name": "Malaysia",
        "officialName": "Malaysia",
        "subregion": "South-Eastern Asia",
        "population": 32365998,
        "flag": "https://flagcdn.com/w320/my.png",
        "yellowFever": false,
        "typhoid": true,
        "malaria": true,
        "jEncephalitis": true,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "India",
        "officialName": "Republic of India",
        "subregion": "Southern Asia",
        "population": 1380004385,
        "flag": "https://flagcdn.com/w320/in.png",
        "yellowFever": false,
        "typhoid": true,
        "malaria": true,
        "jEncephalitis": true,
        "visaRequired": true,
        "travelAdvisory": 2
    },
    {
        "name": "French Southern and Antarctic Lands",
        "officialName": "Territory of the French Southern and Antarctic Lands",
        "population": 400,
        "flag": "https://flagcdn.com/w320/tf.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 0
    },
    {
        "name": "Gibraltar",
        "officialName": "Gibraltar",
        "subregion": "Southern Europe",
        "population": 33691,
        "flag": "https://flagcdn.com/w320/gi.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 0
    },
    {
        "name": "Norfolk Island",
        "officialName": "Territory of Norfolk Island",
        "subregion": "Australia and New Zealand",
        "population": 2302,
        "flag": "https://flagcdn.com/w320/nf.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 0
    },
    {
        "name": "Sudan",
        "officialName": "Republic of the Sudan",
        "subregion": "Northern Africa",
        "population": 43849269,
        "flag": "https://flagcdn.com/w320/sd.png",
        "yellowFever": true,
        "typhoid": false,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 4
    },
    {
        "name": "Saint Vincent and the Grenadines",
        "officialName": "Saint Vincent and the Grenadines",
        "subregion": "Caribbean",
        "population": 110947,
        "flag": "https://flagcdn.com/w320/vc.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "British Virgin Islands",
        "officialName": "Virgin Islands",
        "subregion": "Caribbean",
        "population": 30237,
        "flag": "https://flagcdn.com/w320/vg.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "French Polynesia",
        "officialName": "French Polynesia",
        "subregion": "Polynesia",
        "population": 280904,
        "flag": "https://flagcdn.com/w320/pf.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Monaco",
        "officialName": "Principality of Monaco",
        "subregion": "Western Europe",
        "population": 39244,
        "flag": "https://flagcdn.com/w320/mc.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 2
    },
    {
        "name": "Nepal",
        "officialName": "Federal Democratic Republic of Nepal",
        "subregion": "Southern Asia",
        "population": 29136808,
        "flag": "https://flagcdn.com/w320/np.png",
        "yellowFever": false,
        "typhoid": true,
        "malaria": true,
        "jEncephalitis": true,
        "visaRequired": true,
        "travelAdvisory": 2
    },
    {
        "name": "Uzbekistan",
        "officialName": "Republic of Uzbekistan",
        "subregion": "Central Asia",
        "population": 34232050,
        "flag": "https://flagcdn.com/w320/uz.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 1
    },
    {
        "name": "Fiji",
        "officialName": "Republic of Fiji",
        "subregion": "Melanesia",
        "population": 896444,
        "flag": "https://flagcdn.com/w320/fj.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Mauritius",
        "officialName": "Republic of Mauritius",
        "subregion": "Eastern Africa",
        "population": 1265740,
        "flag": "https://flagcdn.com/w320/mu.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Montenegro",
        "officialName": "Montenegro",
        "subregion": "Southeast Europe",
        "population": 621718,
        "flag": "https://flagcdn.com/w320/me.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Kiribati",
        "officialName": "Independent and Sovereign Republic of Kiribati",
        "subregion": "Micronesia",
        "population": 119446,
        "flag": "https://flagcdn.com/w320/ki.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Equatorial Guinea",
        "officialName": "Republic of Equatorial Guinea",
        "subregion": "Middle Africa",
        "population": 1402985,
        "flag": "https://flagcdn.com/w320/gq.png",
        "yellowFever": true,
        "typhoid": false,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 2
    },
    {
        "name": "Heard Island and McDonald Islands",
        "officialName": "Heard Island and McDonald Islands",
        "population": 0,
        "flag": "https://flagcdn.com/w320/hm.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 0
    },
    {
        "name": "Philippines",
        "officialName": "Republic of the Philippines",
        "subregion": "South-Eastern Asia",
        "population": 109581085,
        "flag": "https://flagcdn.com/w320/ph.png",
        "yellowFever": false,
        "typhoid": true,
        "malaria": true,
        "jEncephalitis": true,
        "visaRequired": false,
        "travelAdvisory": 2
    },
    {
        "name": "Svalbard and Jan Mayen",
        "officialName": "Svalbard og Jan Mayen",
        "subregion": "Northern Europe",
        "population": 2562,
        "flag": "https://flagcdn.com/w320/sj.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 0
    },
    {
        "name": "Cocos (Keeling) Islands",
        "officialName": "Territory of the Cocos (Keeling) Islands",
        "subregion": "Australia and New Zealand",
        "population": 544,
        "flag": "https://flagcdn.com/w320/cc.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 0
    },
    {
        "name": "Mozambique",
        "officialName": "Republic of Mozambique",
        "subregion": "Eastern Africa",
        "population": 31255435,
        "flag": "https://flagcdn.com/w320/mz.png",
        "yellowFever": false,
        "typhoid": true,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 2
    },
    {
        "name": "Suriname",
        "officialName": "Republic of Suriname",
        "subregion": "South America",
        "population": 586634,
        "flag": "https://flagcdn.com/w320/sr.png",
        "yellowFever": true,
        "typhoid": false,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 1
    },
    {
        "name": "Senegal",
        "officialName": "Republic of Senegal",
        "subregion": "Western Africa",
        "population": 16743930,
        "flag": "https://flagcdn.com/w320/sn.png",
        "yellowFever": true,
        "typhoid": true,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 1
    },
    {
        "name": "Syria",
        "officialName": "Syrian Arab Republic",
        "subregion": "Western Asia",
        "population": 17500657,
        "flag": "https://flagcdn.com/w320/sy.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 4
    },
    {
        "name": "Lesotho",
        "officialName": "Kingdom of Lesotho",
        "subregion": "Southern Africa",
        "population": 2142252,
        "flag": "https://flagcdn.com/w320/ls.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "United States Virgin Islands",
        "officialName": "Virgin Islands of the United States",
        "subregion": "Caribbean",
        "population": 106290,
        "flag": "https://flagcdn.com/w320/vi.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 0
    },
    {
        "name": "Cape Verde",
        "officialName": "Republic of Cabo Verde",
        "subregion": "Western Africa",
        "population": 555988,
        "flag": "https://flagcdn.com/w320/cv.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "New Zealand",
        "officialName": "New Zealand",
        "subregion": "Australia and New Zealand",
        "population": 5084300,
        "flag": "https://flagcdn.com/w320/nz.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Latvia",
        "officialName": "Republic of Latvia",
        "subregion": "Northern Europe",
        "population": 1901548,
        "flag": "https://flagcdn.com/w320/lv.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Mauritania",
        "officialName": "Islamic Republic of Mauritania",
        "subregion": "Western Africa",
        "population": 4649660,
        "flag": "https://flagcdn.com/w320/mr.png",
        "yellowFever": true,
        "typhoid": true,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 3
    },
    {
        "name": "Sierra Leone",
        "officialName": "Republic of Sierra Leone",
        "subregion": "Western Africa",
        "population": 7976985,
        "flag": "https://flagcdn.com/w320/sl.png",
        "yellowFever": true,
        "typhoid": true,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 2
    },
    {
        "name": "Thailand",
        "officialName": "Kingdom of Thailand",
        "subregion": "South-Eastern Asia",
        "population": 69799978,
        "flag": "https://flagcdn.com/w320/th.png",
        "yellowFever": false,
        "typhoid": true,
        "malaria": true,
        "jEncephalitis": true,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "United Kingdom",
        "officialName": "United Kingdom of Great Britain and Northern Ireland",
        "subregion": "Northern Europe",
        "population": 67215293,
        "flag": "https://flagcdn.com/w320/gb.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 2
    },
    {
        "name": "Iraq",
        "officialName": "Republic of Iraq",
        "subregion": "Western Asia",
        "population": 40222503,
        "flag": "https://flagcdn.com/w320/iq.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 4
    },
    {
        "name": "Nigeria",
        "officialName": "Federal Republic of Nigeria",
        "subregion": "Western Africa",
        "population": 206139587,
        "flag": "https://flagcdn.com/w320/ng.png",
        "yellowFever": true,
        "typhoid": true,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 3
    },
    {
        "name": "Rwanda",
        "officialName": "Republic of Rwanda",
        "subregion": "Eastern Africa",
        "population": 12952209,
        "flag": "https://flagcdn.com/w320/rw.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 1
    },
    {
        "name": "Libya",
        "officialName": "State of Libya",
        "subregion": "Northern Africa",
        "population": 6871287,
        "flag": "https://flagcdn.com/w320/ly.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 4
    },
    {
        "name": "Australia",
        "officialName": "Commonwealth of Australia",
        "subregion": "Australia and New Zealand",
        "population": 25687041,
        "flag": "https://flagcdn.com/w320/au.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": true,
        "visaRequired": true,
        "travelAdvisory": 1
    },
    {
        "name": "Paraguay",
        "officialName": "Republic of Paraguay",
        "subregion": "South America",
        "population": 7132530,
        "flag": "https://flagcdn.com/w320/py.png",
        "yellowFever": true,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Finland",
        "officialName": "Republic of Finland",
        "subregion": "Northern Europe",
        "population": 5530719,
        "flag": "https://flagcdn.com/w320/fi.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "San Marino",
        "officialName": "Republic of San Marino",
        "subregion": "Southern Europe",
        "population": 33938,
        "flag": "https://flagcdn.com/w320/sm.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 2
    },
    {
        "name": "Bahamas",
        "officialName": "Commonwealth of the Bahamas",
        "subregion": "Caribbean",
        "population": 393248,
        "flag": "https://flagcdn.com/w320/bs.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 2
    },
    {
        "name": "Dominica",
        "officialName": "Commonwealth of Dominica",
        "subregion": "Caribbean",
        "population": 71991,
        "flag": "https://flagcdn.com/w320/dm.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Niger",
        "officialName": "Republic of Niger",
        "subregion": "Western Africa",
        "population": 24206636,
        "flag": "https://flagcdn.com/w320/ne.png",
        "yellowFever": true,
        "typhoid": true,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 4
    },
    {
        "name": "Saint Helena, Ascension and Tristan da Cunha",
        "officialName": "Saint Helena, Ascension and Tristan da Cunha",
        "subregion": "Western Africa",
        "population": 53192,
        "flag": "https://flagcdn.com/w320/sh.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 0
    },
    {
        "name": "Solomon Islands",
        "officialName": "Solomon Islands",
        "subregion": "Melanesia",
        "population": 686878,
        "flag": "https://flagcdn.com/w320/sb.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 2
    },
    {
        "name": "Comoros",
        "officialName": "Union of the Comoros",
        "subregion": "Eastern Africa",
        "population": 869595,
        "flag": "https://flagcdn.com/w320/km.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 1
    },
    {
        "name": "Ghana",
        "officialName": "Republic of Ghana",
        "subregion": "Western Africa",
        "population": 31072945,
        "flag": "https://flagcdn.com/w320/gh.png",
        "yellowFever": true,
        "typhoid": true,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 2
    },
    {
        "name": "United States",
        "officialName": "United States of America",
        "subregion": "North America",
        "population": 329484123,
        "flag": "https://flagcdn.com/w320/us.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 0
    },
    {
        "name": "Malta",
        "officialName": "Republic of Malta",
        "subregion": "Southern Europe",
        "population": 525285,
        "flag": "https://flagcdn.com/w320/mt.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Sweden",
        "officialName": "Kingdom of Sweden",
        "subregion": "Northern Europe",
        "population": 10353442,
        "flag": "https://flagcdn.com/w320/se.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 2
    },
    {
        "name": "Brazil",
        "officialName": "Federative Republic of Brazil",
        "subregion": "South America",
        "population": 212559409,
        "flag": "https://flagcdn.com/w320/br.png",
        "yellowFever": true,
        "typhoid": false,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 2
    },
    {
        "name": "Greece",
        "officialName": "Hellenic Republic",
        "subregion": "Southern Europe",
        "population": 10715549,
        "flag": "https://flagcdn.com/w320/gr.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Namibia",
        "officialName": "Republic of Namibia",
        "subregion": "Southern Africa",
        "population": 2540916,
        "flag": "https://flagcdn.com/w320/na.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Estonia",
        "officialName": "Republic of Estonia",
        "subregion": "Northern Europe",
        "population": 1331057,
        "flag": "https://flagcdn.com/w320/ee.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Tonga",
        "officialName": "Kingdom of Tonga",
        "subregion": "Polynesia",
        "population": 105697,
        "flag": "https://flagcdn.com/w320/to.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Pakistan",
        "officialName": "Islamic Republic of Pakistan",
        "subregion": "Southern Asia",
        "population": 220892331,
        "flag": "https://flagcdn.com/w320/pk.png",
        "yellowFever": false,
        "typhoid": true,
        "malaria": true,
        "jEncephalitis": true,
        "visaRequired": true,
        "travelAdvisory": 3
    },
    {
        "name": "Isle of Man",
        "officialName": "Isle of Man",
        "subregion": "Northern Europe",
        "population": 85032,
        "flag": "https://flagcdn.com/w320/im.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 0
    },
    {
        "name": "Bolivia",
        "officialName": "Plurinational State of Bolivia",
        "subregion": "South America",
        "population": 11673029,
        "flag": "https://flagcdn.com/w320/bo.png",
        "yellowFever": true,
        "typhoid": false,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 2
    },
    {
        "name": "Cyprus",
        "officialName": "Republic of Cyprus",
        "subregion": "Southern Europe",
        "population": 1207361,
        "flag": "https://flagcdn.com/w320/cy.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "South Georgia",
        "officialName": "South Georgia and the South Sandwich Islands",
        "population": 30,
        "flag": "https://flagcdn.com/w320/gs.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 0
    },
    {
        "name": "Kyrgyzstan",
        "officialName": "Kyrgyz Republic",
        "subregion": "Central Asia",
        "population": 6591600,
        "flag": "https://flagcdn.com/w320/kg.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Honduras",
        "officialName": "Republic of Honduras",
        "subregion": "Central America",
        "population": 9904608,
        "flag": "https://flagcdn.com/w320/hn.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 3
    },
    {
        "name": "Antigua and Barbuda",
        "officialName": "Antigua and Barbuda",
        "subregion": "Caribbean",
        "population": 97928,
        "flag": "https://flagcdn.com/w320/ag.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Republic of Congo",
        "officialName": "Republic of the Congo",
        "subregion": "Middle Africa",
        "population": 5657000,
        "flag": "https://flagcdn.com/w320/cg.png",
        "yellowFever": true,
        "typhoid": true,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 2
    },
    {
        "name": "Hong Kong",
        "officialName": "Hong Kong Special Administrative Region of the People's Republic of China",
        "subregion": "Eastern Asia",
        "population": 7500700,
        "flag": "https://flagcdn.com/w320/hk.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 2
    },
    {
        "name": "Italy",
        "officialName": "Italian Republic",
        "subregion": "Southern Europe",
        "population": 59554023,
        "flag": "https://flagcdn.com/w320/it.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 2
    },
    {
        "name": "Cuba",
        "officialName": "Republic of Cuba",
        "subregion": "Caribbean",
        "population": 11326616,
        "flag": "https://flagcdn.com/w320/cu.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 2
    },
    {
        "name": "Antarctica",
        "officialName": "Antarctica",
        "population": 1000,
        "flag": "https://flagcdn.com/w320/aq.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 2
    },
    {
        "name": "Oman",
        "officialName": "Sultanate of Oman",
        "subregion": "Western Asia",
        "population": 5106622,
        "flag": "https://flagcdn.com/w320/om.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 2
    },
    {
        "name": "Vatican City",
        "officialName": "Vatican City State",
        "subregion": "Southern Europe",
        "population": 451,
        "flag": "https://flagcdn.com/w320/va.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 2
    },
    {
        "name": "Bahrain",
        "officialName": "Kingdom of Bahrain",
        "subregion": "Western Asia",
        "population": 1701583,
        "flag": "https://flagcdn.com/w320/bh.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 2
    },
    {
        "name": "Uruguay",
        "officialName": "Oriental Republic of Uruguay",
        "subregion": "South America",
        "population": 3473727,
        "flag": "https://flagcdn.com/w320/uy.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 2
    },
    {
        "name": "Yemen",
        "officialName": "Republic of Yemen",
        "subregion": "Western Asia",
        "population": 29825968,
        "flag": "https://flagcdn.com/w320/ye.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 4
    },
    {
        "name": "Cambodia",
        "officialName": "Kingdom of Cambodia",
        "subregion": "South-Eastern Asia",
        "population": 16718971,
        "flag": "https://flagcdn.com/w320/kh.png",
        "yellowFever": false,
        "typhoid": true,
        "malaria": true,
        "jEncephalitis": true,
        "visaRequired": true,
        "travelAdvisory": 1
    },
    {
        "name": "Morocco",
        "officialName": "Kingdom of Morocco",
        "subregion": "Northern Africa",
        "population": 36910558,
        "flag": "https://flagcdn.com/w320/ma.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 2
    },
    {
        "name": "Saint Barthélemy",
        "officialName": "Collectivity of Saint Barthélemy",
        "subregion": "Caribbean",
        "population": 4255,
        "flag": "https://flagcdn.com/w320/bl.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Kosovo",
        "officialName": "Republic of Kosovo",
        "subregion": "Southeast Europe",
        "population": 1775378,
        "flag": "https://flagcdn.com/w320/xk.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 2
    },
    {
        "name": "Slovakia",
        "officialName": "Slovak Republic",
        "subregion": "Central Europe",
        "population": 5458827,
        "flag": "https://flagcdn.com/w320/sk.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Saint Martin",
        "officialName": "Saint Martin",
        "subregion": "Caribbean",
        "population": 38659,
        "flag": "https://flagcdn.com/w320/mf.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Wallis and Futuna",
        "officialName": "Territory of the Wallis and Futuna Islands",
        "subregion": "Polynesia",
        "population": 11750,
        "flag": "https://flagcdn.com/w320/wf.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 0
    },
    {
        "name": "Botswana",
        "officialName": "Republic of Botswana",
        "subregion": "Southern Africa",
        "population": 2351625,
        "flag": "https://flagcdn.com/w320/bw.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "France",
        "officialName": "French Republic",
        "subregion": "Western Europe",
        "population": 67391582,
        "flag": "https://flagcdn.com/w320/fr.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 2
    },
    {
        "name": "Spain",
        "officialName": "Kingdom of Spain",
        "subregion": "Southern Europe",
        "population": 47351567,
        "flag": "https://flagcdn.com/w320/es.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 2
    },
    {
        "name": "Christmas Island",
        "officialName": "Territory of Christmas Island",
        "subregion": "Australia and New Zealand",
        "population": 2072,
        "flag": "https://flagcdn.com/w320/cx.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Zambia",
        "officialName": "Republic of Zambia",
        "subregion": "Eastern Africa",
        "population": 18383956,
        "flag": "https://flagcdn.com/w320/zm.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Croatia",
        "officialName": "Republic of Croatia",
        "subregion": "Southeast Europe",
        "population": 4047200,
        "flag": "https://flagcdn.com/w320/hr.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Armenia",
        "officialName": "Republic of Armenia",
        "subregion": "Western Asia",
        "population": 2963234,
        "flag": "https://flagcdn.com/w320/am.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 2
    },
    {
        "name": "Palau",
        "officialName": "Republic of Palau",
        "subregion": "Micronesia",
        "population": 18092,
        "flag": "https://flagcdn.com/w320/pw.png",
        "yellowFever": false,
        "typhoid": true,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Trinidad and Tobago",
        "officialName": "Republic of Trinidad and Tobago",
        "subregion": "Caribbean",
        "population": 1399491,
        "flag": "https://flagcdn.com/w320/tt.png",
        "yellowFever": true,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 3
    },
    {
        "name": "Andorra",
        "officialName": "Principality of Andorra",
        "subregion": "Southern Europe",
        "population": 77265,
        "flag": "https://flagcdn.com/w320/ad.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Algeria",
        "officialName": "People's Democratic Republic of Algeria",
        "subregion": "Northern Africa",
        "population": 44700000,
        "flag": "https://flagcdn.com/w320/dz.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 2
    },
    {
        "name": "Micronesia",
        "officialName": "Federated States of Micronesia",
        "subregion": "Micronesia",
        "population": 115021,
        "flag": "https://flagcdn.com/w320/fm.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Belize",
        "officialName": "Belize",
        "subregion": "Central America",
        "population": 397621,
        "flag": "https://flagcdn.com/w320/bz.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 2
    },
    {
        "name": "Taiwan",
        "officialName": "Republic of China (Taiwan)",
        "subregion": "Eastern Asia",
        "population": 23503349,
        "flag": "https://flagcdn.com/w320/tw.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": true,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Tunisia",
        "officialName": "Tunisian Republic",
        "subregion": "Northern Africa",
        "population": 11818618,
        "flag": "https://flagcdn.com/w320/tn.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 2
    },
    {
        "name": "Åland Islands",
        "officialName": "Åland Islands",
        "subregion": "Northern Europe",
        "population": 29458,
        "flag": "https://flagcdn.com/w320/ax.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Haiti",
        "officialName": "Republic of Haiti",
        "subregion": "Caribbean",
        "population": 11402533,
        "flag": "https://flagcdn.com/w320/ht.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 4
    },
    {
        "name": "Sint Maarten",
        "officialName": "Sint Maarten",
        "subregion": "Caribbean",
        "population": 40812,
        "flag": "https://flagcdn.com/w320/sx.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Chad",
        "officialName": "Republic of Chad",
        "subregion": "Middle Africa",
        "population": 16425859,
        "flag": "https://flagcdn.com/w320/td.png",
        "yellowFever": true,
        "typhoid": true,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 3
    },
    {
        "name": "Liechtenstein",
        "officialName": "Principality of Liechtenstein",
        "subregion": "Western Europe",
        "population": 38137,
        "flag": "https://flagcdn.com/w320/li.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Dominican Republic",
        "officialName": "Dominican Republic",
        "subregion": "Caribbean",
        "population": 10847904,
        "flag": "https://flagcdn.com/w320/do.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 2
    },
    {
        "name": "Bouvet Island",
        "officialName": "Bouvet Island",
        "population": 0,
        "flag": "https://flagcdn.com/w320/bv.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 0
    },
    {
        "name": "Central African Republic",
        "officialName": "Central African Republic",
        "subregion": "Middle Africa",
        "population": 4829764,
        "flag": "https://flagcdn.com/w320/cf.png",
        "yellowFever": true,
        "typhoid": false,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 4
    },
    {
        "name": "Austria",
        "officialName": "Republic of Austria",
        "subregion": "Central Europe",
        "population": 8917205,
        "flag": "https://flagcdn.com/w320/at.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Singapore",
        "officialName": "Republic of Singapore",
        "subregion": "South-Eastern Asia",
        "population": 5685807,
        "flag": "https://flagcdn.com/w320/sg.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": true,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Canada",
        "officialName": "Canada",
        "subregion": "North America",
        "population": 38005238,
        "flag": "https://flagcdn.com/w320/ca.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Greenland",
        "officialName": "Greenland",
        "subregion": "North America",
        "population": 56367,
        "flag": "https://flagcdn.com/w320/gl.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Angola",
        "officialName": "Republic of Angola",
        "subregion": "Middle Africa",
        "population": 32866268,
        "flag": "https://flagcdn.com/w320/ao.png",
        "yellowFever": true,
        "typhoid": false,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 2
    },
    {
        "name": "Tajikistan",
        "officialName": "Republic of Tajikistan",
        "subregion": "Central Asia",
        "population": 9537642,
        "flag": "https://flagcdn.com/w320/tj.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 2
    },
    {
        "name": "Portugal",
        "officialName": "Portuguese Republic",
        "subregion": "Southern Europe",
        "population": 10305564,
        "flag": "https://flagcdn.com/w320/pt.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Eswatini",
        "officialName": "Kingdom of Eswatini",
        "subregion": "Southern Africa",
        "population": 1160164,
        "flag": "https://flagcdn.com/w320/sz.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 2
    },
    {
        "name": "Somalia",
        "officialName": "Federal Republic of Somalia",
        "subregion": "Eastern Africa",
        "population": 15893219,
        "flag": "https://flagcdn.com/w320/so.png",
        "yellowFever": false,
        "typhoid": true,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 4
    },
    {
        "name": "Guyana",
        "officialName": "Co-operative Republic of Guyana",
        "subregion": "South America",
        "population": 786559,
        "flag": "https://flagcdn.com/w320/gy.png",
        "yellowFever": true,
        "typhoid": false,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 3
    },
    {
        "name": "Ivory Coast",
        "officialName": "Republic of Côte d'Ivoire",
        "subregion": "Western Africa",
        "population": 26378275,
        "flag": "https://flagcdn.com/w320/ci.png",
        "yellowFever": false,
        "typhoid": true,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 2
    },
    {
        "name": "Maldives",
        "officialName": "Republic of the Maldives",
        "subregion": "Southern Asia",
        "population": 540542,
        "flag": "https://flagcdn.com/w320/mv.png",
        "yellowFever": false,
        "typhoid": true,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 2
    },
    {
        "name": "Seychelles",
        "officialName": "Republic of Seychelles",
        "subregion": "Eastern Africa",
        "population": 98462,
        "flag": "https://flagcdn.com/w320/sc.png",
        "yellowFever": false,
        "typhoid": true,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Aruba",
        "officialName": "Aruba",
        "subregion": "Caribbean",
        "population": 106766,
        "flag": "https://flagcdn.com/w320/aw.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Egypt",
        "officialName": "Arab Republic of Egypt",
        "subregion": "Northern Africa",
        "population": 102334403,
        "flag": "https://flagcdn.com/w320/eg.png",
        "yellowFever": false,
        "typhoid": true,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 3
    },
    {
        "name": "Madagascar",
        "officialName": "Republic of Madagascar",
        "subregion": "Eastern Africa",
        "population": 27691019,
        "flag": "https://flagcdn.com/w320/mg.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 2
    },
    {
        "name": "Zimbabwe",
        "officialName": "Republic of Zimbabwe",
        "subregion": "Southern Africa",
        "population": 14862927,
        "flag": "https://flagcdn.com/w320/zw.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 2
    },
    {
        "name": "South Korea",
        "officialName": "Republic of Korea",
        "subregion": "Eastern Asia",
        "population": 51780579,
        "flag": "https://flagcdn.com/w320/kr.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Eritrea",
        "officialName": "State of Eritrea",
        "subregion": "Eastern Africa",
        "population": 5352000,
        "flag": "https://flagcdn.com/w320/er.png",
        "yellowFever": false,
        "typhoid": true,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 2
    },
    {
        "name": "Jamaica",
        "officialName": "Jamaica",
        "subregion": "Caribbean",
        "population": 2961161,
        "flag": "https://flagcdn.com/w320/jm.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 3
    },
    {
        "name": "Uganda",
        "officialName": "Republic of Uganda",
        "subregion": "Eastern Africa",
        "population": 45741000,
        "flag": "https://flagcdn.com/w320/ug.png",
        "yellowFever": true,
        "typhoid": true,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 3
    },
    {
        "name": "Cayman Islands",
        "officialName": "Cayman Islands",
        "subregion": "Caribbean",
        "population": 65720,
        "flag": "https://flagcdn.com/w320/ky.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "American Samoa",
        "officialName": "American Samoa",
        "subregion": "Polynesia",
        "population": 55197,
        "flag": "https://flagcdn.com/w320/as.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Mongolia",
        "officialName": "Mongolia",
        "subregion": "Eastern Asia",
        "population": 3278292,
        "flag": "https://flagcdn.com/w320/mn.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Luxembourg",
        "officialName": "Grand Duchy of Luxembourg",
        "subregion": "Western Europe",
        "population": 632275,
        "flag": "https://flagcdn.com/w320/lu.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Guinea",
        "officialName": "Republic of Guinea",
        "subregion": "Western Africa",
        "population": 13132792,
        "flag": "https://flagcdn.com/w320/gn.png",
        "yellowFever": true,
        "typhoid": true,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 2
    },
    {
        "name": "North Macedonia",
        "officialName": "Republic of North Macedonia",
        "subregion": "Southeast Europe",
        "population": 2077132,
        "flag": "https://flagcdn.com/w320/mk.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Bhutan",
        "officialName": "Kingdom of Bhutan",
        "subregion": "Southern Asia",
        "population": 771612,
        "flag": "https://flagcdn.com/w320/bt.png",
        "yellowFever": false,
        "typhoid": true,
        "malaria": true,
        "jEncephalitis": true,
        "visaRequired": true,
        "travelAdvisory": 1
    },
    {
        "name": "Peru",
        "officialName": "Republic of Peru",
        "subregion": "South America",
        "population": 32971846,
        "flag": "https://flagcdn.com/w320/pe.png",
        "yellowFever": true,
        "typhoid": false,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 2
    },
    {
        "name": "United States Minor Outlying Islands",
        "officialName": "United States Minor Outlying Islands",
        "subregion": "North America",
        "population": 300,
        "flag": "https://flagcdn.com/w320/um.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Kazakhstan",
        "officialName": "Republic of Kazakhstan",
        "subregion": "Central Asia",
        "population": 18754440,
        "flag": "https://flagcdn.com/w320/kz.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Gabon",
        "officialName": "Gabonese Republic",
        "subregion": "Middle Africa",
        "population": 2225728,
        "flag": "https://flagcdn.com/w320/ga.png",
        "yellowFever": true,
        "typhoid": false,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 1
    },
    {
        "name": "Liberia",
        "officialName": "Republic of Liberia",
        "subregion": "Western Africa",
        "population": 5057677,
        "flag": "https://flagcdn.com/w320/lr.png",
        "yellowFever": true,
        "typhoid": true,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 2
    },
    {
        "name": "Switzerland",
        "officialName": "Swiss Confederation",
        "subregion": "Western Europe",
        "population": 8654622,
        "flag": "https://flagcdn.com/w320/ch.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Qatar",
        "officialName": "State of Qatar",
        "subregion": "Western Asia",
        "population": 2881060,
        "flag": "https://flagcdn.com/w320/qa.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 1
    },
    {
        "name": "Argentina",
        "officialName": "Argentine Republic",
        "subregion": "South America",
        "population": 45376763,
        "flag": "https://flagcdn.com/w320/ar.png",
        "yellowFever": true,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Falkland Islands",
        "officialName": "Falkland Islands",
        "subregion": "South America",
        "population": 2563,
        "flag": "https://flagcdn.com/w320/fk.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 0
    },
    {
        "name": "Guam",
        "officialName": "Guam",
        "subregion": "Micronesia",
        "population": 168783,
        "flag": "https://flagcdn.com/w320/gu.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Panama",
        "officialName": "Republic of Panama",
        "subregion": "Central America",
        "population": 4314768,
        "flag": "https://flagcdn.com/w320/pa.png",
        "yellowFever": true,
        "typhoid": false,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 2
    },
    {
        "name": "Saint Pierre and Miquelon",
        "officialName": "Saint Pierre and Miquelon",
        "subregion": "North America",
        "population": 6069,
        "flag": "https://flagcdn.com/w320/pm.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 0
    },
    {
        "name": "Caribbean Netherlands",
        "officialName": "Bonaire, Sint Eustatius and Saba",
        "subregion": "Caribbean",
        "population": 25987,
        "flag": "https://flagcdn.com/w320/bq.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 0
    },
    {
        "name": "Norway",
        "officialName": "Kingdom of Norway",
        "subregion": "Northern Europe",
        "population": 5379475,
        "flag": "https://flagcdn.com/w320/no.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Turks and Caicos Islands",
        "officialName": "Turks and Caicos Islands",
        "subregion": "Caribbean",
        "population": 38718,
        "flag": "https://flagcdn.com/w320/tc.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 2
    },
    {
        "name": "Bosnia and Herzegovina",
        "officialName": "Bosnia and Herzegovina",
        "subregion": "Southeast Europe",
        "population": 3280815,
        "flag": "https://flagcdn.com/w320/ba.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 2
    },
    {
        "name": "Mali",
        "officialName": "Republic of Mali",
        "subregion": "Western Africa",
        "population": 20250834,
        "flag": "https://flagcdn.com/w320/ml.png",
        "yellowFever": true,
        "typhoid": true,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 4
    },
    {
        "name": "Burkina Faso",
        "officialName": "Burkina Faso",
        "subregion": "Western Africa",
        "population": 20903278,
        "flag": "https://flagcdn.com/w320/bf.png",
        "yellowFever": true,
        "typhoid": true,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 4
    },
    {
        "name": "Afghanistan",
        "officialName": "Islamic Republic of Afghanistan",
        "subregion": "Southern Asia",
        "population": 40218234,
        "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_the_Taliban.svg/320px-Flag_of_the_Taliban.svg.png",
        "yellowFever": false,
        "typhoid": true,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 4
    },
    {
        "name": "Slovenia",
        "officialName": "Republic of Slovenia",
        "subregion": "Central Europe",
        "population": 2100126,
        "flag": "https://flagcdn.com/w320/si.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "French Guiana",
        "officialName": "Guiana",
        "subregion": "South America",
        "population": 254541,
        "flag": "https://flagcdn.com/w320/gf.png",
        "yellowFever": true,
        "typhoid": false,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Iceland",
        "officialName": "Iceland",
        "subregion": "Northern Europe",
        "population": 366425,
        "flag": "https://flagcdn.com/w320/is.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Bulgaria",
        "officialName": "Republic of Bulgaria",
        "subregion": "Southeast Europe",
        "population": 6927288,
        "flag": "https://flagcdn.com/w320/bg.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Georgia",
        "officialName": "Georgia",
        "subregion": "Western Asia",
        "population": 3714000,
        "flag": "https://flagcdn.com/w320/ge.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Montserrat",
        "officialName": "Montserrat",
        "subregion": "Caribbean",
        "population": 4922,
        "flag": "https://flagcdn.com/w320/ms.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Ireland",
        "officialName": "Republic of Ireland",
        "subregion": "Northern Europe",
        "population": 4994724,
        "flag": "https://flagcdn.com/w320/ie.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Burundi",
        "officialName": "Republic of Burundi",
        "subregion": "Eastern Africa",
        "population": 11890781,
        "flag": "https://flagcdn.com/w320/bi.png",
        "yellowFever": true,
        "typhoid": true,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 3
    },
    {
        "name": "Northern Mariana Islands",
        "officialName": "Commonwealth of the Northern Mariana Islands",
        "subregion": "Micronesia",
        "population": 57557,
        "flag": "https://flagcdn.com/w320/mp.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 0
    },
    {
        "name": "Grenada",
        "officialName": "Grenada",
        "subregion": "Caribbean",
        "population": 112519,
        "flag": "https://flagcdn.com/w320/gd.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Belgium",
        "officialName": "Kingdom of Belgium",
        "subregion": "Western Europe",
        "population": 11555997,
        "flag": "https://flagcdn.com/w320/be.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 2
    },
    {
        "name": "Albania",
        "officialName": "Republic of Albania",
        "subregion": "Southeast Europe",
        "population": 2837743,
        "flag": "https://flagcdn.com/w320/al.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 2
    },
    {
        "name": "Denmark",
        "officialName": "Kingdom of Denmark",
        "subregion": "Northern Europe",
        "population": 5831404,
        "flag": "https://flagcdn.com/w320/dk.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 2
    },
    {
        "name": "Colombia",
        "officialName": "Republic of Colombia",
        "subregion": "South America",
        "population": 50882884,
        "flag": "https://flagcdn.com/w320/co.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 3
    },
    {
        "name": "Lithuania",
        "officialName": "Republic of Lithuania",
        "subregion": "Northern Europe",
        "population": 2794700,
        "flag": "https://flagcdn.com/w320/lt.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Jersey",
        "officialName": "Bailiwick of Jersey",
        "subregion": "Northern Europe",
        "population": 100800,
        "flag": "https://flagcdn.com/w320/je.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 0
    },
    {
        "name": "Kuwait",
        "officialName": "State of Kuwait",
        "subregion": "Western Asia",
        "population": 4270563,
        "flag": "https://flagcdn.com/w320/kw.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 1
    },
    {
        "name": "Bangladesh",
        "officialName": "People's Republic of Bangladesh",
        "subregion": "Southern Asia",
        "population": 164689383,
        "flag": "https://flagcdn.com/w320/bd.png",
        "yellowFever": false,
        "typhoid": true,
        "malaria": true,
        "jEncephalitis": true,
        "visaRequired": true,
        "travelAdvisory": 2
    },
    {
        "name": "Gambia",
        "officialName": "Republic of the Gambia",
        "subregion": "Western Africa",
        "population": 2416664,
        "flag": "https://flagcdn.com/w320/gm.png",
        "yellowFever": true,
        "typhoid": true,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 2
    },
    {
        "name": "Pitcairn Islands",
        "officialName": "Pitcairn Group of Islands",
        "subregion": "Polynesia",
        "population": 56,
        "flag": "https://flagcdn.com/w320/pn.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 0
    },
    {
        "name": "Western Sahara",
        "officialName": "Sahrawi Arab Democratic Republic",
        "subregion": "Northern Africa",
        "population": 510713,
        "flag": "https://flagcdn.com/w320/eh.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 0
    },
    {
        "name": "Vietnam",
        "officialName": "Socialist Republic of Vietnam",
        "subregion": "South-Eastern Asia",
        "population": 97338583,
        "flag": "https://flagcdn.com/w320/vn.png",
        "yellowFever": false,
        "typhoid": true,
        "malaria": true,
        "jEncephalitis": true,
        "visaRequired": true,
        "travelAdvisory": 1
    },
    {
        "name": "Réunion",
        "officialName": "Réunion Island",
        "subregion": "Eastern Africa",
        "population": 840974,
        "flag": "https://flagcdn.com/w320/re.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 0
    },
    {
        "name": "Germany",
        "officialName": "Federal Republic of Germany",
        "subregion": "Western Europe",
        "population": 83240525,
        "flag": "https://flagcdn.com/w320/de.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 2
    },
    {
        "name": "Ecuador",
        "officialName": "Republic of Ecuador",
        "subregion": "South America",
        "population": 17643060,
        "flag": "https://flagcdn.com/w320/ec.png",
        "yellowFever": true,
        "typhoid": false,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 2
    },
    {
        "name": "Hungary",
        "officialName": "Hungary",
        "subregion": "Central Europe",
        "population": 9749763,
        "flag": "https://flagcdn.com/w320/hu.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Ethiopia",
        "officialName": "Federal Democratic Republic of Ethiopia",
        "subregion": "Eastern Africa",
        "population": 114963583,
        "flag": "https://flagcdn.com/w320/et.png",
        "yellowFever": true,
        "typhoid": true,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 3
    },
    {
        "name": "Saint Lucia",
        "officialName": "Saint Lucia",
        "subregion": "Caribbean",
        "population": 183629,
        "flag": "https://flagcdn.com/w320/lc.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Vanuatu",
        "officialName": "Republic of Vanuatu",
        "subregion": "Melanesia",
        "population": 307150,
        "flag": "https://flagcdn.com/w320/vu.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "North Korea",
        "officialName": "Democratic People's Republic of Korea",
        "subregion": "Eastern Asia",
        "population": 25778815,
        "flag": "https://flagcdn.com/w320/kp.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": true,
        "jEncephalitis": true,
        "visaRequired": true,
        "travelAdvisory": 4
    },
    {
        "name": "Netherlands",
        "officialName": "Kingdom of the Netherlands",
        "subregion": "Western Europe",
        "population": 16655799,
        "flag": "https://flagcdn.com/w320/nl.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 2
    },
    {
        "name": "Guatemala",
        "officialName": "Republic of Guatemala",
        "subregion": "Central America",
        "population": 16858333,
        "flag": "https://flagcdn.com/w320/gt.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 3
    },
    {
        "name": "Russia",
        "officialName": "Russian Federation",
        "subregion": "Eastern Europe",
        "population": 144104080,
        "flag": "https://flagcdn.com/w320/ru.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": true,
        "visaRequired": true,
        "travelAdvisory": 4
    },
    {
        "name": "Mexico",
        "officialName": "United Mexican States",
        "subregion": "North America",
        "population": 128932753,
        "flag": "https://flagcdn.com/w320/mx.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 2
    },
    {
        "name": "Marshall Islands",
        "officialName": "Republic of the Marshall Islands",
        "subregion": "Micronesia",
        "population": 59194,
        "flag": "https://flagcdn.com/w320/mh.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Martinique",
        "officialName": "Martinique",
        "subregion": "Caribbean",
        "population": 378243,
        "flag": "https://flagcdn.com/w320/mq.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Chile",
        "officialName": "Republic of Chile",
        "subregion": "South America",
        "population": 19116209,
        "flag": "https://flagcdn.com/w320/cl.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 2
    },
    {
        "name": "Macau",
        "officialName": "Macao Special Administrative Region of the People's Republic of China",
        "subregion": "Eastern Asia",
        "population": 649342,
        "flag": "https://flagcdn.com/w320/mo.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": true,
        "visaRequired": false,
        "travelAdvisory": 3
    },
    {
        "name": "Costa Rica",
        "officialName": "Republic of Costa Rica",
        "subregion": "Central America",
        "population": 5094114,
        "flag": "https://flagcdn.com/w320/cr.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 2
    },
    {
        "name": "Djibouti",
        "officialName": "Republic of Djibouti",
        "subregion": "Eastern Africa",
        "population": 988002,
        "flag": "https://flagcdn.com/w320/dj.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 2
    },
    {
        "name": "Japan",
        "officialName": "Japan",
        "subregion": "Eastern Asia",
        "population": 125836021,
        "flag": "https://flagcdn.com/w320/jp.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": true,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Azerbaijan",
        "officialName": "Republic of Azerbaijan",
        "subregion": "Western Asia",
        "population": 10110116,
        "flag": "https://flagcdn.com/w320/az.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 2
    },
    {
        "name": "Malawi",
        "officialName": "Republic of Malawi",
        "subregion": "Eastern Africa",
        "population": 19129955,
        "flag": "https://flagcdn.com/w320/mw.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 2
    },
    {
        "name": "El Salvador",
        "officialName": "Republic of El Salvador",
        "subregion": "Central America",
        "population": 6486201,
        "flag": "https://flagcdn.com/w320/sv.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 3
    },
    {
        "name": "Israel",
        "officialName": "State of Israel",
        "subregion": "Western Asia",
        "population": 9216900,
        "flag": "https://flagcdn.com/w320/il.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 2
    },
    {
        "name": "Kenya",
        "officialName": "Republic of Kenya",
        "subregion": "Eastern Africa",
        "population": 53771300,
        "flag": "https://flagcdn.com/w320/ke.png",
        "yellowFever": true,
        "typhoid": true,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 2
    },
    {
        "name": "Cook Islands",
        "officialName": "Cook Islands",
        "subregion": "Polynesia",
        "population": 18100,
        "flag": "https://flagcdn.com/w320/ck.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 0
    },
    {
        "name": "South Sudan",
        "officialName": "Republic of South Sudan",
        "subregion": "Middle Africa",
        "population": 11193729,
        "flag": "https://flagcdn.com/w320/ss.png",
        "yellowFever": true,
        "typhoid": true,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 4
    },
    {
        "name": "Timor-Leste",
        "officialName": "Democratic Republic of Timor-Leste",
        "subregion": "South-Eastern Asia",
        "population": 1318442,
        "flag": "https://flagcdn.com/w320/tl.png",
        "yellowFever": false,
        "typhoid": true,
        "malaria": true,
        "jEncephalitis": true,
        "visaRequired": true,
        "travelAdvisory": 2
    },
    {
        "name": "Poland",
        "officialName": "Republic of Poland",
        "subregion": "Central Europe",
        "population": 37950802,
        "flag": "https://flagcdn.com/w320/pl.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Anguilla",
        "officialName": "Anguilla",
        "subregion": "Caribbean",
        "population": 13452,
        "flag": "https://flagcdn.com/w320/ai.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Barbados",
        "officialName": "Barbados",
        "subregion": "Caribbean",
        "population": 287371,
        "flag": "https://flagcdn.com/w320/bb.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Turkey",
        "officialName": "Republic of Turkey",
        "subregion": "Western Asia",
        "population": 84339067,
        "flag": "https://flagcdn.com/w320/tr.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 2
    },
    {
        "name": "Belarus",
        "officialName": "Republic of Belarus",
        "subregion": "Eastern Europe",
        "population": 9398861,
        "flag": "https://flagcdn.com/w320/by.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 4
    },
    {
        "name": "Guinea-Bissau",
        "officialName": "Republic of Guinea-Bissau",
        "subregion": "Western Africa",
        "population": 1967998,
        "flag": "https://flagcdn.com/w320/gw.png",
        "yellowFever": true,
        "typhoid": false,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 3
    },
    {
        "name": "Nicaragua",
        "officialName": "Republic of Nicaragua",
        "subregion": "Central America",
        "population": 6624554,
        "flag": "https://flagcdn.com/w320/ni.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 3
    },
    {
        "name": "Puerto Rico",
        "officialName": "Commonwealth of Puerto Rico",
        "subregion": "Caribbean",
        "population": 3194034,
        "flag": "https://flagcdn.com/w320/pr.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Laos",
        "officialName": "Lao People's Democratic Republic",
        "subregion": "South-Eastern Asia",
        "population": 7275556,
        "flag": "https://flagcdn.com/w320/la.png",
        "yellowFever": false,
        "typhoid": true,
        "malaria": true,
        "jEncephalitis": true,
        "visaRequired": true,
        "travelAdvisory": 2
    },
    {
        "name": "Jordan",
        "officialName": "Hashemite Kingdom of Jordan",
        "subregion": "Western Asia",
        "population": 10203140,
        "flag": "https://flagcdn.com/w320/jo.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 2
    },
    {
        "name": "Moldova",
        "officialName": "Republic of Moldova",
        "subregion": "Eastern Europe",
        "population": 2617820,
        "flag": "https://flagcdn.com/w320/md.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 2
    },
    {
        "name": "São Tomé and Príncipe",
        "officialName": "Democratic Republic of São Tomé and Príncipe",
        "subregion": "Middle Africa",
        "population": 219161,
        "flag": "https://flagcdn.com/w320/st.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Niue",
        "officialName": "Niue",
        "subregion": "Polynesia",
        "population": 1470,
        "flag": "https://flagcdn.com/w320/nu.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 0
    },
    {
        "name": "Curaçao",
        "officialName": "Country of Curaçao",
        "subregion": "Caribbean",
        "population": 155014,
        "flag": "https://flagcdn.com/w320/cw.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "Democratic Republic of Congo",
        "officialName": "Democratic Republic of the Congo",
        "subregion": "Middle Africa",
        "population": 108407721,
        "flag": "https://flagcdn.com/w320/cd.png",
        "yellowFever": true,
        "typhoid": true,
        "malaria": true,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 3
    },
    {
        "name": "Lebanon",
        "officialName": "Lebanese Republic",
        "subregion": "Western Asia",
        "population": 6825442,
        "flag": "https://flagcdn.com/w320/lb.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 3
    },
    {
        "name": "Myanmar",
        "officialName": "Republic of the Union of Myanmar",
        "subregion": "South-Eastern Asia",
        "population": 54409794,
        "flag": "https://flagcdn.com/w320/mm.png",
        "yellowFever": false,
        "typhoid": true,
        "malaria": true,
        "jEncephalitis": true,
        "visaRequired": true,
        "travelAdvisory": 4
    },
    {
        "name": "Turkmenistan",
        "officialName": "Turkmenistan",
        "subregion": "Central Asia",
        "population": 6031187,
        "flag": "https://flagcdn.com/w320/tm.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": true,
        "travelAdvisory": 2
    },
    {
        "name": "Samoa",
        "officialName": "Independent State of Samoa",
        "subregion": "Polynesia",
        "population": 198410,
        "flag": "https://flagcdn.com/w320/ws.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    },
    {
        "name": "New Caledonia",
        "officialName": "New Caledonia",
        "subregion": "Melanesia",
        "population": 271960,
        "flag": "https://flagcdn.com/w320/nc.png",
        "yellowFever": false,
        "typhoid": false,
        "malaria": false,
        "jEncephalitis": false,
        "visaRequired": false,
        "travelAdvisory": 1
    }
];